# Oracle settings
spring.datasource:
  url: jdbc:postgresql://localhost:5432/pizzashop
  username: postgres
  password: mysecretpassword
  driver-class-name: org.postgresql.Driver


# Hibernate settings
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto: create-drop

# HikariCP settings
# spring.datasource.hikari.*
spring.datasource.hikari:
  connection-timeout: 60000
  maximum-pool-size: 5
                   

logging.level.org.springframework.transaction: ERROR

ribbon:
  eureka:
    enabled: false
  listOfServers: localhost:8081
---
spring:
  sleuth:
    enabled: true
  zipkin:
    enabled: false